### ISSUE TITLE
???

### ISSUE THREAD

**Issue by foobar1123** [sails101/low-level-sockets#1]
{"error":"No `data` specified- please specify data to send."}

**Comment by TemaSM** [comment]
Just look at the 
`api/controllers/SocketController.js` [line 83](https://github.com/sails101/low-level-sockets/blob/master/api/controllers/SocketController.js#L83)
or/and
`api/controllers/SocketController.js` [line 94](https://github.com/sails101/low-level-sockets/blob/master/api/controllers/SocketController.js#L94)
or/and
`api/controllers/SocketController.js` [line 104](https://github.com/sails101/low-level-sockets/blob/master/api/controllers/SocketController.js#L104)
